### ISSUE TITLE
Switch to using cmake for generating build scripts

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#20]
If we did, we wouldn't need to have a makefile and visual studio stuff, we could just have the cmake file.

**Comment by liam-middlebrook** [comment]
At this point NuGet (Visual Studio) allows for a seamless development process on windows. Switching over to CMake would stop from our ability to use NuGet, causing dependency hell once again.
I'm going to close this issue for now because implementing CMake would end out as more of a detriment than a benefit, but in the future this may not be true.
