### ISSUE TITLE
The set of is running is in the drawing thread, but should be in the updating thread

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#9]
Changing this would make it so that programmers can set is running to false in the update thread in order to get the game to exit, instead of in the drawing thread.

**Comment by liam-middlebrook** [comment]
This issue was fixed in the latest commit https://github.com/GearChicken/MINX/commit/22d537dda5ec8901d6f39f75970518914829a163

@brpylko please close issues if you fix them. Also please commit chunks of code that are changed for different reasons separately, this allows a better flow of information if someone is reading over a repositories commit history.

**Comment by JenniferPylko** [comment]
Yeah, I just hadn't gotten around to closing this issue, yet. And yes, that was my mistake for putting both of these things in one commit.

**Comment by liam-middlebrook** [comment]
It's totally okay, I just want to try and keep a level of standards for this repo.
